config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :posts
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, presence: true
  validates :body, presence: true

  has_many :post_tags
  has_many :tags, through: :post_tags
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, uniqueness: true

  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save!
      redirect_to posts_path
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Postが削除されました"
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name,:body, { tag_ids: [] })
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  def index
    @tags = Tag.all
  end

  def show
    @posts = @tag.posts
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name,:body, { tag_ids: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Category</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>編集</h1>
<h3>投稿する</h3>
<%= form_with model: @post, local: true do |f| %>
  <p>タイトル</p>
    <%= f.text_field :name %>
  <p>内容</p>
    <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
  <%= link_to "#{post.name}", post_path(post) %><br>
  <%#= link_to "#{post.tags.each {|t| puts t.name }}", tag_path(post) %><br>
<% end %>

<br>
<%= link_to "新規作成", new_post_path %><br>

app/views/posts/new.html.erb
<h3>投稿する</h3>
<%= form_with model: @post, local: true do |p| %>
  <p>タイトル</p>
    <%= p.text_field :name %>
  <p>内容</p>
    <%= p.text_area :body %><br>
    <%= p.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %> 
      <%= tag.label do %>
        <%= tag.check_box %>
        <%= tag.text %>
      <% end %>
    <% end %><br>
  <%= p.submit %>
<% end %>

app/views/posts/show.html.erb
<h1>詳細</h1>
<%= @post.body %>
<% @post.tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag) %>
<% end %>
<%= link_to "編集", edit_post_path(@post) %>
<%= link_to "削除", @post, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<h1>カテゴリ一覧</h1>
<% @tags.each do |t| %>
  <%= link_to "#{t.name}", tag_path(t) %>
<% end %>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to "#{post.name}", post_path(post) %></li>
  <% end %>
</ul>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>